server:
   port: 8081
spring:
   activiti:
      #启用activiti的身份关系
      check-process-definitions: true
      #保存所有的历史信息
      history-level: full
      #数据库自动建表，在启动后改为false
      database-schema-update: true
      #启用activiti的身份关系
      check-process-definitions: true
      #bpmn文件所在位置
      process-definition-location-prefix: classpath:/processes/
      
   datasource:
      url: jdbc:mysql://localhost:3306/activiti?useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root      
   